# Generated by Django 3.2.5 on 2024-02-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
