# Generated by Django 3.2.5 on 2024-02-29 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0002_message_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
