# Generated by Django 3.2.5 on 2024-02-29 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0003_remove_message_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
