# Generated by Django 3.2.5 on 2024-03-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0004_remove_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=400),
        ),
    ]
