# Generated by Django 3.2.5 on 2024-02-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game_mode',
            field=models.CharField(max_length=20),
        ),
    ]
