# Generated by Django 3.2.5 on 2024-02-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_alter_customuser_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
