# Generated by Django 3.2.5 on 2024-02-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
